name: flutter_application_1
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.10.4

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  shared_preferences: ^2.2.2
  flutter_map: ^6.1.0
  latlong2: ^0.9.0
  http: ^1.1.0
  geolocator: ^10.1.0
  image_picker: ^1.0.7   
  vibration: ^2.0.1  
  auto_route: ^9.0.0  

  camera: ^0.10.5
  path_provider: ^2.1.1
  path: ^1.8.3 
  firebase_core: ^4.3.0
  firebase_auth: ^6.1.3
  cloud_firestore: ^6.1.1
  firebase_storage: ^13.0.5

dependency_overrides:
  image_picker_for_web: ^3.0.4
  
dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  build_runner: ^2.4.13
  auto_route_generator: ^9.0.0

flutter:
  uses-material-design: true
  

  assets:
    - assets/